# Generated by Django 6.0.3 on 2026-04-02 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilStyliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_marque", models.CharField(max_length=100)),
                ("contact_whatsapp", models.CharField(max_length=20)),
                (
                    "photo_profil",
                    models.ImageField(blank=True, null=True, upload_to="profils/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Creation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="creations/")),
                ("description", models.TextField(blank=True)),
                ("date_post", models.DateTimeField(auto_now_add=True)),
                (
                    "styliste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hub.profilstyliste",
                    ),
                ),
            ],
        ),
    ]
