# Generated by Django 6.0.3 on 2026-04-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Immobilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bien",
                    models.CharField(
                        choices=[("terrain", "Terrain"), ("apparte", "Appartement")],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("prix", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="immo/")),
            ],
        ),
    ]
