# Generated by Django 6.0.3 on 2026-04-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_event_immobilier"),
    ]

    operations = [
        migrations.AddField(
            model_name="creation",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="creation",
            name="prix",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
