# Generated by Django 6.0.3 on 2026-04-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_creation_disponible_creation_prix"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilstyliste",
            name="biographie",
            field=models.TextField(
                blank=True, help_text="Présentez votre parcours et votre style."
            ),
        ),
    ]
