# Generated by Django 6.0.3 on 2026-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_profilstyliste_biographie"),
    ]

    operations = [
        migrations.AddField(
            model_name="creation",
            name="image_dos",
            field=models.ImageField(blank=True, null=True, upload_to="creations/"),
        ),
    ]
