# Generated by Django 6.0.4 on 2026-04-10 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0005_creation_image_dos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creation",
            options={
                "ordering": ["-date_post"],
                "verbose_name": "Création",
                "verbose_name_plural": "Créations",
            },
        ),
        migrations.AddField(
            model_name="creation",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="creation",
            name="public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="immobilier",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="immobilier",
            name="public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="creation",
            name="styliste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creations",
                to="hub.profilstyliste",
            ),
        ),
        migrations.AlterField(
            model_name="immobilier",
            name="type_bien",
            field=models.CharField(
                choices=[("terrain", "Terrain"), ("appartement", "Appartement")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profilstyliste",
            name="biographie",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profilstyliste",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
