# Generated by Django 6.0.4 on 2026-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_alter_creation_options_creation_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creation",
            name="image_dos_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="creation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="creations/"),
        ),
    ]
