# Generated by Django 6.0.4 on 2026-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_creation_image_dos_url_alter_creation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creation",
            name="image_dos_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
