# Generated by Django 6.0.4 on 2026-04-11 22:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_alter_creation_image_dos_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creation",
            name="image_dos_url",
        ),
        migrations.RemoveField(
            model_name="creation",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="creation",
            name="public_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="event",
            name="public_id",
        ),
        migrations.RemoveField(
            model_name="immobilier",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="immobilier",
            name="public_id",
        ),
        migrations.AlterField(
            model_name="creation",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="creations"
            ),
        ),
        migrations.AlterField(
            model_name="creation",
            name="image_dos",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="creations_dos"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="events"
            ),
        ),
        migrations.AlterField(
            model_name="immobilier",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="immo"
            ),
        ),
        migrations.AlterField(
            model_name="profilstyliste",
            name="photo_profil",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profils"
            ),
        ),
    ]
