# Generated by Django 6.0.4 on 2026-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0009_remove_creation_image_dos_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creation",
            name="image_dos_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="creation",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="creation",
            name="public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="immobilier",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="immobilier",
            name="public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="creation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="creations/"),
        ),
        migrations.AlterField(
            model_name="creation",
            name="image_dos",
            field=models.ImageField(blank=True, null=True, upload_to="creations/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="immobilier",
            name="image",
            field=models.ImageField(upload_to="immo/"),
        ),
        migrations.AlterField(
            model_name="profilstyliste",
            name="photo_profil",
            field=models.ImageField(blank=True, null=True, upload_to="profils/"),
        ),
    ]
