# Generated by Django 6.0.4 on 2026-04-12 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_creation_image_dos_url_creation_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilstyliste",
            name="photo_profil",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
