# Generated by Django 6.0.4 on 2026-04-28 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0011_alter_profilstyliste_photo_profil"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilstyliste",
            name="date_inscription",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profilstyliste",
            name="email_verifie",
            field=models.BooleanField(default=False),
        ),
    ]
