# Generated by Django 6.0.4 on 2026-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0013_alter_profilstyliste_user_profilproprietaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilstyliste",
            name="is_fake",
            field=models.BooleanField(default=False),
        ),
    ]
