# Generated by Django 6.0.4 on 2026-06-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0014_profilstyliste_is_fake"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationStyliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code d'invitation"
                    ),
                ),
                (
                    "est_utilise",
                    models.BooleanField(default=False, verbose_name="Déjà utilisé ?"),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Code d'invitation Styliste",
                "verbose_name_plural": "Codes d'invitation Stylistes",
            },
        ),
        migrations.RemoveField(
            model_name="profilstyliste",
            name="is_fake",
        ),
    ]
