# Generated by Django 6.0.4 on 2026-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0015_invitationstyliste_remove_profilstyliste_is_fake"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordonnée GPS — ex: 6.131900 (Lomé)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordonnée GPS — ex: 1.222800 (Lomé)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
